AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GetUsersByID:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: RDS_lambda/index.handler
      Runtime: nodejs18.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::398231878389:role/RdsAccess'
      RuntimePolicy:
        UpdateRuntimeOn: Auto
